"""initial tables

Revision ID: 92aa65cf37bb
Revises: 
Create Date: 2026-05-12 12:34:59.513656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92aa65cf37bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('warehouse', sa.String(), nullable=True),
    sa.Column('database_name', sa.String(), nullable=True),
    sa.Column('schema_name', sa.String(), nullable=True),
    sa.Column('org_name', sa.String(), nullable=True),
    sa.Column('generation_status', sa.String(), nullable=True),
    sa.Column('generation_progress', sa.Text(), nullable=True),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.Column('push_status', sa.String(), nullable=True),
    sa.Column('push_progress', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snowflake_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('asset_level', sa.String(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('full_path', sa.String(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('is_nullable', sa.Boolean(), nullable=True),
    sa.Column('sf_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['snowflake_assets.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['connection_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('physical_asset_id', sa.UUID(), nullable=True),
    sa.Column('layer', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('collibra_asset_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['physical_asset_id'], ['snowflake_assets.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['connection_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_assets')
    op.drop_table('snowflake_assets')
    op.drop_table('connection_sessions')
    # ### end Alembic commands ###
